<?php
	$activity_expiry_time = 90;
	$adm_style = 'default';
	$cache_expiry = 0;
	$css_compression = true;
	$default_action = 'index';
	$default_controller = 'home';
	$default_language = 'pl';
	$gzip_compression = true;
	$gzip_compression_level = 1;
	$helpers_autoload = array('main_functions');
	$js_compression = true;
	$languages = array('pl' => 'Polski',  'en' => 'English');
	$load_user_interfaces = true;
	$lock_time_login_failed = 900;
	$lock_time_captcha_failed = 300;
	$max_login_failed_attempts = 3;
	$max_captcha_failed_attempts = 5;
	$multilingual = true;
	$reduce_http_requests = true;
	$site_disabled = false;
	$statistics = true;
	$style = 'default';
